class ImgAssets {
  static const assets = 'assets/images/';

  static const String logInAc = '${assets}loginac.png';
  static const String logInArt = '${assets}loginillus.png';
  static const String createAc = '${assets}createac.png';
  static const String fonIcon = '${assets}fon.png';
  static const String google = '${assets}Google.png';
  static const String startNeet = '${assets}startyourneet.png';
  static const String otpArt = '${assets}OTP.png';
  static const String calendarIcon = '${assets}calendarIcon.png';
  static const String messageIcon = '${assets}messageIcon.png';
  static const String arrowDown = '${assets}down.png';
  static const String homeNav = '${assets}home2.png';
  static const String listNav = '${assets}list2.png';
  static const String uspNav = '${assets}usp.png';
  static const String userNav = '${assets}user2.png';
  static const String personIllus = '${assets}elluser.png';
  static const String banner = '${assets}backgrnd.png';
  static const String timeTaken = '${assets}timetaken.png';
  static const String accuracy = '${assets}accuracy.png';
  static const String review = '${assets}review.png';
  static const String retake = '${assets}retake.png';
  static const String share = '${assets}share.png';
  static const String bookMark = '${assets}bookmark.png';
  static const String infoCircle = '${assets}info-circle.png';
  static const String questionImg = '${assets}question-img.png';
  static const String optionImg = '${assets}option-img.png';
  static const String solutionImg = '${assets}solution-img.png';
  static const String timer = '${assets}timer.png';
  static const String pause = '${assets}pause-circle.png';
  static const String more = '${assets}more.png';
  static const String arrowCircleRight = '${assets}arrow-circle-right.png';
  static const String customTest = '${assets}custom-test.png';
  static const String mockTest = '${assets}mock-test.png';
  static const String mockTestBig = '${assets}mock-test-big.png';
  static const String closCircle = '${assets}close-circle.png';
  static const String edit = '${assets}edit.png';
}
